version: '3.8'
services:
    app:
        platform: linux/amd64
        container_name: sis-laravel-api
        hostname: sis-laravel-api
        build:
            context: ./
            dockerfile: Dockerfile
        image: seati/sis-laravel-api:1.0
        restart: unless-stopped
        environment:
            SERVICE_NAME: sis-laravel-api
            SERVICE_TAGS: dev
        working_dir: /var/www/
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9003:9003"
        networks:
            - api-sis-laravel

    nginx:
        platform: linux/amd64
        container_name: sis-laravel-api-nginx
        hostname: sis-laravel-api-nginx
        domainname: ${APP_DOMAIN_NAME:-localhost.test}
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - api-sis-laravel

    # db mysql
    db:
        image: mysql:5.7.22
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - api-sis-laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - api-sis-laravel

networks:
    api-sis-laravel:
        name: sis-laravel
        driver: bridge
